"""One-off: rewrite the three project notebooks to reflect the dataset/extractor
changes made on 2026-05-26:

  * Records with no known author (HC3 humans) are dropped via
    --require-known-author.
  * Every kept sample's author must contribute >=2 human texts as TRACE context
    (after rewrite-source exclusion) -- enforced by --min-human-siblings 2.
    Effect: HC3-AI, ArguGPT and RAID are all dropped (they have no human
    siblings), plus USE singleton authors. Kept set is USE-only.
  * TRACE runs in `author` mode with the same-author / human-only / no-source-
    leakage sibling rule.

Final counts after the rebuild:
  train  4,051  (703 human + 3,348 AI rewrites)  -- all USE
  val      667  (116 + 551)
  test     829  (144 + 685)

The script edits in place: data/dataset_overview.ipynb,
training/full_pipeline.ipynb, models/analysis.ipynb. Run once; safe to re-run.

Stale output cells are cleared in places where values will change after the
rebuild; the user re-runs the notebooks top-to-bottom to repopulate them.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def _code(src: str, outputs: list | None = None) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": outputs if outputs is not None else [],
        "source": src.splitlines(keepends=True),
    }


def _load(nb_path: Path) -> dict:
    return json.loads(nb_path.read_text(encoding="utf-8"))


def _save(nb_path: Path, nb: dict) -> None:
    nb_path.write_text(json.dumps(nb, indent=1) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# 1. data/dataset_overview.ipynb
# ---------------------------------------------------------------------------

def rewrite_dataset_overview(nb_path: Path) -> None:
    cells = [
        _md(
            "# Dataset Overview\n"
            "\n"
            "This notebook documents the dataset used to train and evaluate the human-vs-AI text detector in this repository. It covers:\n"
            "\n"
            "1. **The raw text corpus** — `data/dataset_ready_final/*.jsonl`. Humans, AI-original texts, and LLM rewrites.\n"
            "2. **The training filter** — every sample's author must contribute at least 2 human texts as TRACE context. This makes the training set USE-only: HC3 humans (no author), HC3-AI, ArguGPT, RAID (model-as-author with no humans), and USE authors with too few essays are all excluded.\n"
            "3. **The cached extractor features** — `data/features/*.npz`. NELA + StyleDecipher + TRACE feature triples consumed by training.\n"
            "4. **How to unpack `features.tar.gz`** if you've just downloaded the built cache off a remote GPU.\n"
            "\n"
            "For the full dataset-construction story (sources, rewrite generators, quality filtering, author-disjoint splitting), see [`README.md`](README.md). For training/evaluation, see [`../training/README.md`](../training/README.md)."
        ),
        _md(
            "## 1. The raw text corpus\n"
            "\n"
            "The corpus combines three types of records, split **author-disjoint** into train/val/test so the TRACE author-fingerprint model cannot leak author identity across splits.\n"
            "\n"
            "| Type | Label | Count | Description |\n"
            "|---|---|---|---|\n"
            "| Human texts | `human` | 3,415 | USE student essays + HC3 human answers |\n"
            "| AI-original texts | `ai`    | 3,620 | ArguGPT, RAID, HC3 ChatGPT answers |\n"
            "| LLM rewrites of human texts | `ai` | 6,051 | 5 LLMs paraphrasing USE essays (style-shift stress test) |\n"
            "| **Total (raw `.jsonl`)** | | **13,086** | |\n"
            "\n"
            "**Per-split totals in the raw `.jsonl` (before the known-author filter):**\n"
            "\n"
            "| Split | Total | Human | AI |\n"
            "|---|---|---|---|\n"
            "| `train` | 9,265 | 2,406 | 6,859 |\n"
            "| `val`   | 1,846 |   492 | 1,354 |\n"
            "| `test`  | 1,975 |   517 | 1,458 |\n"
            "\n"
            "Every record (in every `.jsonl`) shares the same schema:\n"
            "\n"
            "| Field | Type | Meaning |\n"
            "|---|---|---|\n"
            "| `id` | `str` | unique ID (`h_` human, `a_` AI-original, `r_` rewrite) |\n"
            "| `text` | `str` | the text content |\n"
            "| `is_ai` / `label` | `bool` / `str` | redundant binary label |\n"
            "| `source` | `str` | `use`, `use_rewrite`, `hc3`, `argugpt`, `raid` |\n"
            "| `author_id` | `str?` | USE author (rewrites inherit their source's author) |\n"
            "| `model` | `str?` | generating model for AI / rewrite records |\n"
            "| `source_text_id` | `str?` | for rewrites: the source human record's `id` |\n"
            "| `split` | `str` | `train` / `val` / `test` |"
        ),
        _md(
            "## 2. The known-author + ≥2-sibling filter\n"
            "\n"
            "Two stacked filters narrow the raw corpus down to records suitable for TRACE-style author profiling:\n"
            "\n"
            "1. **`--require-known-author`** — drops records whose author is unknown. HC3 humans were scraped from open Q&A and have no per-author identity (`human_author_id` and `generator` are both null), so the filter discards them.\n"
            "2. **`--min-human-siblings 2`** — for each remaining sample, count the same-author HUMAN texts available as TRACE context (excluding the source-text of an LLM rewrite, to block original↔rewrite leakage). Drop the sample if that count is < 2.\n"
            "\n"
            "Effect of the second filter:\n"
            "\n"
            "* **HC3-AI, ArguGPT, RAID** all have a *generator* (model) as their `author_id` with no human siblings → 0 humans by that author → dropped.\n"
            "* **USE singleton authors** (USE students who contributed only 1–2 essays) → dropped.\n"
            "* **USE authors with ≥3 essays** → kept. Every kept sample has ≥2 humans to compare against in TRACE.\n"
            "\n"
            "Net effect: **the training set is USE-only** (USE original essays + their LLM rewrites). Non-USE sources contribute nothing to training under this rule.\n"
            "\n"
            "**Records dropped by the filters:**\n"
            "\n"
            "| Split | Raw | After `--require-known-author` | After `--min-human-siblings 2` (kept) |\n"
            "|---|---|---|---|\n"
            "| `train` | 9,265 | 7,767 | **4,051** |\n"
            "| `val`   | 1,846 | 1,526 |   **667** |\n"
            "| `test`  | 1,975 | 1,650 |   **829** |\n"
            "\n"
            "**Class balance.** Each USE author contributes ~3 human essays + ~15 LLM rewrites (5 LLMs × ~3 essays), so the human:AI ratio is consistently **~1:4.76** in every split. Training still uses inverse-frequency class weighting; the *strict-FPR* deployment regime is unaffected (it operates on probability ranking, not class balance)."
        ),
        _md(
            "## 3. The cached extractor features\n"
            "\n"
            "Running the three feature extractors (NELA, StyleDecipher, TRACE) over every record is slow — StyleDecipher in particular calls 5 LLMs per non-cluster record. To make training fast and repeatable, `training/build_dataset.py` runs the extractors **once** and caches the result. The training scripts then never touch the extractors.\n"
            "\n"
            "The cache lives at `data/features/`:\n"
            "\n"
            "| File | Contents |\n"
            "|---|---|\n"
            "| `train.npz` | feature arrays for the filtered train split |\n"
            "| `val.npz`   | feature arrays for the filtered val split |\n"
            "| `test.npz`  | feature arrays for the filtered test split |\n"
            "| `meta.json` | build configuration + per-split summary stats |\n"
            "\n"
            "Each `.npz` contains row-aligned arrays:\n"
            "\n"
            "| Array | Shape | Description |\n"
            "|---|---|---|\n"
            "| `nela`     | (N, 87)  | NELA surface / linguistic / credibility features |\n"
            "| `style`    | (N, 10)  | StyleDecipher: mean + std of 5 similarity metrics vs LLM rewrites |\n"
            "| `trace`    | (N, 128) | TRACE author-style embedding |\n"
            "| `label`    | (N,)     | 0 = human, 1 = ai |\n"
            "| `style_ok` | (N,)     | True if real StyleDecipher features were computed (False → zero vector) |\n"
            "| `ids`      | (N,)     | record IDs from the source `.jsonl` (row ↔ record) |\n"
            "| `sources`  | (N,)     | source corpus name (matches the `.jsonl` `source` field) |\n"
            "\n"
            "**TRACE mode (`trace_context = \"author\"`).** TRACE produces an author-aware embedding instead of a single-text one. For each sample, the embedding is computed from:\n"
            "\n"
            "* the sample's own text (always), plus\n"
            "* the sample author's *other* HUMAN texts, **excluding** the source-text of an LLM rewrite (to block original↔rewrite leakage).\n"
            "\n"
            "After the `--min-human-siblings 2` filter, the kept set is USE-only and every sample's TRACE context is genuinely author-aware:\n"
            "\n"
            "| Source | Typical # of human siblings | TRACE context |\n"
            "|---|---|---|\n"
            "| `use` (human essay) | 2–4 | author's other USE essays |\n"
            "| `use_rewrite` (LLM rewrite) | 2–4 | author's other USE essays, minus the source |\n"
            "\n"
            "**StyleDecipher coverage note.** `style_ok` distinguishes records that actually got LLM rewrites compared against them from ones that didn't. In `--styledecipher ollama` mode (what this cache was built with), every record's text was sent to 5 LLMs that produced fresh rewrites, so `style_ok` should be ~100 % across every source corpus."
        ),
        _md(
            "## 4. Extract `features.tar.gz`\n"
            "\n"
            "If you just downloaded the built cache from a remote GPU as `features.tar.gz`, the next cell unpacks it into `data/features/`. Safe to re-run — it's a no-op if `data/features/` already exists."
        ),
        _code(
            "import tarfile\n"
            "from pathlib import Path\n"
            "\n"
            "# Resolve paths relative to this notebook (works whether you launch from repo root or data/)\n"
            "NB_DIR       = Path.cwd() if Path.cwd().name == \"data\" else Path.cwd() / \"data\"\n"
            "REPO_ROOT    = NB_DIR.parent\n"
            "FEATURES_DIR = NB_DIR / \"features\"\n"
            "TARBALL      = REPO_ROOT / \"features.tar.gz\"\n"
            "\n"
            "if FEATURES_DIR.exists() and any(FEATURES_DIR.glob(\"*.npz\")):\n"
            "    print(f\"already unpacked: {FEATURES_DIR}\")\n"
            "elif TARBALL.exists():\n"
            "    print(f\"extracting {TARBALL.name} → {REPO_ROOT}\")\n"
            "    with tarfile.open(TARBALL) as t:\n"
            "        t.extractall(REPO_ROOT)\n"
            "    print(f\"done  → {FEATURES_DIR}\")\n"
            "else:\n"
            "    raise FileNotFoundError(\n"
            "        f\"Neither {FEATURES_DIR} nor {TARBALL} exists.\\n\"\n"
            "        f\"Either rebuild the cache (see ../training/README.md) or place features.tar.gz at the repo root.\"\n"
            "    )\n"
            "\n"
            "print(\"\\nfiles in data/features/:\")\n"
            "for p in sorted(FEATURES_DIR.iterdir()):\n"
            "    print(f\"  {p.name:<14} {p.stat().st_size/1024:>8.1f} KB\")"
        ),
        _md(
            "## 5. Load the cache and read the build configuration\n"
            "\n"
            "`meta.json` records exactly how the cache was built — the most important fields after the 2026-05-26 rebuild are `trace_context`, `require_known_author`, and `rebuild_note` (only present when a smart TRACE-only re-extraction was used to avoid re-running Ollama)."
        ),
        _code(
            "import json\n"
            "import numpy as np\n"
            "\n"
            "meta = json.loads((FEATURES_DIR / \"meta.json\").read_text())\n"
            "\n"
            "print(\"Build configuration:\")\n"
            "print(f\"  styledecipher_mode   = {meta.get('styledecipher_mode')}\")\n"
            "print(f\"  trace_context        = {meta.get('trace_context')}\")\n"
            "print(f\"  require_known_author = {meta.get('require_known_author', False)}\")\n"
            "print(f\"  min_human_siblings   = {meta.get('min_human_siblings', 0)}\")\n"
            "print(f\"  dims                 = {meta['dims']}\")\n"
            "print(f\"  seed                 = {meta.get('seed')}\")\n"
            "if meta.get('rebuild_note'):\n"
            "    print(f\"  rebuild_note         = {meta['rebuild_note']}\")\n"
            "\n"
            "print(\"\\nPer-split summary (from meta.json):\")\n"
            "for sp, stats in meta[\"splits\"].items():\n"
            "    extras = []\n"
            "    if stats.get(\"dropped_no_author\"):\n"
            "        extras.append(f\"-{stats['dropped_no_author']} no-author\")\n"
            "    if stats.get(\"dropped_low_siblings\"):\n"
            "        extras.append(f\"-{stats['dropped_low_siblings']} <{meta.get('min_human_siblings', 0)} sibs\")\n"
            "    extra = (\"  (\" + \", \".join(extras) + \")\") if extras else \"\"\n"
            "    print(f\"  {sp:<5} records={stats['records']:>5}  human={stats['human']:>5}  ai={stats['ai']:>5}  \"\n"
            "          f\"style_coverage={stats['style_coverage']:.1%}{extra}\")\n"
            "\n"
            "splits = {sp: np.load(FEATURES_DIR / f\"{sp}.npz\", allow_pickle=True) for sp in (\"train\", \"val\", \"test\")}\n"
            "print(\"\\nArrays per split:\", list(splits[\"train\"].files))"
        ),
        _md(
            "## 6. Per-extractor sanity check\n"
            "\n"
            "Each row carries three feature vectors. Confirm each extractor populated real (non-zero) values across every split, and look at their numeric ranges.\n"
            "\n"
            "**Important — all three extractors must contribute.** A zero NELA row means NELA crashed on that text; a zero StyleDecipher row means no rewrites were available; a zero TRACE row should never happen (TRACE always has at least the sample's own text to embed). If any extractor's non-zero rate falls below ~99 %, investigate before training."
        ),
        _code(
            "for sp in (\"train\", \"val\", \"test\"):\n"
            "    d = splits[sp]\n"
            "    n = len(d[\"ids\"])\n"
            "    print(f\"\\n=== {sp} ({n} records) ===\")\n"
            "    for name in (\"nela\", \"style\", \"trace\"):\n"
            "        arr = d[name]\n"
            "        nz  = int((arr != 0).any(axis=1).sum())\n"
            "        print(f\"  {name:<5} shape={str(arr.shape):<12} non-zero rows: {nz:>5}/{n}  \"\n"
            "              f\"mean={arr.mean():+.4f}  std={arr.std():.4f}  min={arr.min():+.4f}  max={arr.max():+.4f}\")"
        ),
        _md(
            "## 7. StyleDecipher coverage broken down by source corpus\n"
            "\n"
            "Health check for the `ollama`-mode build. Every source — including the non-cluster ones (`hc3`, `argugpt`, `raid`) that require fresh Ollama generations — should hit ~100 % `style_ok`. Anything materially lower means Ollama was down or rejecting requests for some records during the build."
        ),
        _code(
            "from collections import defaultdict\n"
            "\n"
            "for sp in (\"train\", \"val\", \"test\"):\n"
            "    d = splits[sp]\n"
            "    buckets = defaultdict(list)\n"
            "    for s, ok in zip(d[\"sources\"], d[\"style_ok\"]):\n"
            "        buckets[str(s)].append(bool(ok))\n"
            "    print(f\"\\n--- {sp} ---\")\n"
            "    for src in sorted(buckets):\n"
            "        oks = buckets[src]\n"
            "        print(f\"  {src:<14} {sum(oks):>5}/{len(oks):<5} = {sum(oks)/len(oks):.0%}\")"
        ),
        _md(
            "## 8. Label distribution\n"
            "\n"
            "After the `min_human_siblings=2` filter the kept set is USE-only — every author has ≥3 essays, contributing 1 human + 5 LLM rewrites per essay. The human:AI ratio is therefore a clean ~1:4.76 in every split:\n"
            "\n"
            "| Split | Human | AI | Ratio |\n"
            "|---|---|---|---|\n"
            "| `train` | 703 | 3,348 | 1:4.76 |\n"
            "| `val`   | 116 |   551 | 1:4.75 |\n"
            "| `test`  | 144 |   685 | 1:4.76 |\n"
            "\n"
            "Training still uses inverse-frequency class weighting on this ratio."
        ),
        _code(
            "for sp in (\"train\", \"val\", \"test\"):\n"
            "    labels = splits[sp][\"label\"]\n"
            "    human  = int((labels == 0).sum())\n"
            "    ai     = int((labels == 1).sum())\n"
            "    total  = len(labels)\n"
            "    print(f\"  {sp:<5} human={human:>5} ({human/total:.1%})   ai={ai:>5} ({ai/total:.1%})   total={total}\")"
        ),
        _md(
            "## 9. TRACE sibling stats — how strong is the author context?\n"
            "\n"
            "Under `min_human_siblings=2`, every kept sample's author contributes ≥2 human texts (after rewrite-source exclusion). The distribution shows that filter at work: no zero-sibling rows survive, and most samples have 2–4 siblings (USE authors mostly have 3 essays)."
        ),
        _code(
            "import sys\n"
            "from pathlib import Path\n"
            "sys.path.insert(0, str(REPO_ROOT))\n"
            "from data.preprocessing import Dataset\n"
            "\n"
            "def human_siblings(sample, ds):\n"
            "    \"\"\"Same rule the rebuild used: same-author humans, minus the source-text of rewrites.\"\"\"\n"
            "    out = []\n"
            "    for s in ds._by_author.get(sample.author_id, []):\n"
            "        if s.record_id == sample.record_id:           continue\n"
            "        if s.label != \"human\":                         continue\n"
            "        if sample.is_rewrite and s.record_id == sample.source_text_id: continue\n"
            "        out.append(s)\n"
            "    return out\n"
            "\n"
            "MIN_SIBS = meta.get(\"min_human_siblings\", 0)\n"
            "\n"
            "for sp in (\"train\", \"val\", \"test\"):\n"
            "    ds = Dataset.load(sp)\n"
            "    by_source = {}\n"
            "    for s in ds:\n"
            "        if not s.has_known_author:\n"
            "            continue\n"
            "        n = len(human_siblings(s, ds))\n"
            "        if n < MIN_SIBS:                                                # mirror the build-time filter\n"
            "            continue\n"
            "        by_source.setdefault(s.source, []).append(n)\n"
            "    print(f\"\\n--- {sp} (kept samples only, filter min_human_siblings={MIN_SIBS}) ---\")\n"
            "    for src in sorted(by_source):\n"
            "        ns = by_source[src]\n"
            "        bucket_min = min(ns); bucket_max = max(ns)\n"
            "        avg = sum(ns) / len(ns)\n"
            "        print(f\"  {src:<14} n={len(ns):>5}  human_siblings min/avg/max = {bucket_min}/{avg:.2f}/{bucket_max}\")"
        ),
        _md(
            "## 10. Where to go next\n"
            "\n"
            "The cache is ready to feed into training and evaluation. Everything below runs locally on CPU/GPU and never touches the extractors:\n"
            "\n"
            "```bash\n"
            "# (Re)build the cache from scratch — slow, calls Ollama for StyleDecipher rewrites\n"
            "python -m training.build_dataset --splits all --styledecipher ollama \\\n"
            "                                --trace-context author \\\n"
            "                                --require-known-author --min-human-siblings 2\n"
            "\n"
            "# Cheap rebuild that PRESERVES the Ollama-derived StyleDecipher + NELA values\n"
            "# and only recomputes TRACE in author mode (used after switching trace_context).\n"
            "# Uses --min-human-siblings 2 by default.\n"
            "python -m training.rebuild_trace_author\n"
            "\n"
            "# Neural fusion model — one strategy or sweep all four\n"
            "python -m training.train --fusion-method gating\n"
            "python -m training.train --fusion-method all\n"
            "\n"
            "# Classical classifier — one backend or sweep all\n"
            "python -m training.train_classical --classifier xgboost\n"
            "python -m training.train_classical --classifier all\n"
            "\n"
            "# Evaluate any trained checkpoint on the test split (.pt or .joblib auto-detected)\n"
            "python -m test.evaluate --model models/test_models/fusion_gating.pt\n"
            "```\n"
            "\n"
            "See [`../training/README.md`](../training/README.md) for the full training framework documentation — classifier choices, hyper-parameters, fusion strategies, and per-extractor importance reporting for classical models."
        ),
    ]

    nb = _load(nb_path)
    nb["cells"] = cells
    _save(nb_path, nb)
    print(f"wrote {nb_path}  ({len(cells)} cells)")


# ---------------------------------------------------------------------------
# 2. training/full_pipeline.ipynb
# ---------------------------------------------------------------------------

def rewrite_full_pipeline(nb_path: Path) -> None:
    cells = [
        _md(
            "# Full training & evaluation pipeline\n"
            "\n"
            "This notebook trains and evaluates **all 10 candidate models** end-to-end on the cached extractor features, then re-evaluates every one of them at a **strict decision threshold that holds FPR ≤ 1 %** (where the positive class is `ai`, so FP = a human text falsely flagged as AI).\n"
            "\n"
            "Run cells top-to-bottom. Expected runtime: **~30–60 minutes on CPU** (neural training dominates), **~5–10 minutes on GPU**. All 10 trained checkpoints are saved to `models/ready_models/`.\n"
            "\n"
            "**Prerequisite — the cache must reflect the 2026-05-26 rebuild:**\n"
            "\n"
            "* `meta.json` should say `\"trace_context\": \"author\"`, `\"require_known_author\": true`, and `\"min_human_siblings\": 2`.\n"
            "* Split sizes should be `train = 4,051`, `val = 667`, `test = 829` (USE-only after the ≥2-sibling filter).\n"
            "* If those don't match, rebuild via `python -m training.build_dataset --splits all --styledecipher ollama --trace-context author --require-known-author --min-human-siblings 2`, or recover the prior cache via the smart helper `python -m training.rebuild_trace_author` (default `--min-human-siblings 2`)."
        ),
        _md(
            "## Architecture\n"
            "\n"
            "Three feature extractors produce a (87 + 10 + 128 = 225)-dim feature triple per text. Two parallel training tracks consume the same cache:\n"
            "\n"
            "```\n"
            "                  ┌─ NELA          (87)  surface / linguistic features\n"
            "  text  ────────► ├─ StyleDecipher (10)  similarity vs 5 LLM rewrites (mean + std of 5 metrics)\n"
            "                  └─ TRACE         (128) author-style embedding\n"
            "                       │                 ├─ context: same-author HUMAN texts\n"
            "                       │                 └─ source-text of rewrites excluded (no leakage)\n"
            "                       │\n"
            "                       ├──► Neural fusion track   (4 strategies)  → 4 .pt   checkpoints\n"
            "                       │      concat | mlp | attention | gating\n"
            "                       │      MultiFeatureFusion → 2-class softmax head\n"
            "                       │\n"
            "                       └──► Classical track       (6 backends)    → 6 .joblib checkpoints\n"
            "                              xgboost | random_forest | logreg | svm | hist_gbm | gradient_boosting\n"
            "                              feature triple flattened to 225-dim → model fits directly\n"
            "```\n"
            "\n"
            "The **10 models** we'll train and compare:\n"
            "\n"
            "| Track | Models |\n"
            "|---|---|\n"
            "| Neural fusion | `concat`, `mlp`, `attention`, `gating` |\n"
            "| Classical | `xgboost`, `random_forest`, `logreg`, `svm`, `hist_gbm`, `gradient_boosting` |\n"
            "\n"
            "Classical tree/linear models additionally report **per-extractor feature importance** — answering the core question of this repo: *how much does each extractor contribute?*\n"
            "\n"
            "**All three extractors are load-bearing.** None is allowed to silently degrade to a zero vector at scale. The sanity check in section 2 confirms StyleDecipher coverage is ~100 % and TRACE values are non-zero — if either dips, stop and rebuild before training, otherwise the per-extractor importance numbers below get distorted."
        ),
        _md("## 1. Setup — imports, paths, sanity check"),
        _code(
            "import sys, json\n"
            "from pathlib import Path\n"
            "\n"
            "# Make sure the repo root is on sys.path so the training package imports work\n"
            "NB_DIR = Path.cwd() if Path.cwd().name == \"training\" else Path.cwd() / \"training\"\n"
            "REPO_ROOT = NB_DIR.parent\n"
            "if str(REPO_ROOT) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO_ROOT))\n"
            "\n"
            "import numpy as np\n"
            "from sklearn.metrics import (\n"
            "    accuracy_score, f1_score, precision_recall_fscore_support,\n"
            "    confusion_matrix, roc_curve, roc_auc_score,\n"
            ")\n"
            "\n"
            "from training import paths\n"
            "from training.config import TrainConfig, FUSION_METHODS\n"
            "from training.feature_dataset import FeatureNormalizer, FusionFeatureDataset\n"
            "from training.classical import BACKENDS, ClassicalClassifier, flatten_features\n"
            "from training.model import FusionClassifier\n"
            "from training.train import train_one as train_neural_one\n"
            "from training.train_classical import train_one as train_classical_one\n"
            "\n"
            "FEATURE_DIR = paths.FEATURE_DIR\n"
            "SAVE_DIR    = paths.READY_MODELS_DIR\n"
            "SAVE_DIR.mkdir(parents=True, exist_ok=True)\n"
            "\n"
            "for sp in (\"train\", \"val\", \"test\"):\n"
            "    assert (FEATURE_DIR / f\"{sp}.npz\").exists(), (\n"
            "        f\"missing {sp}.npz — run `python -m training.build_dataset --splits all \"\n"
            "        \"--styledecipher ollama --trace-context author --require-known-author \"\n"
            "        \"--min-human-siblings 2` first\"\n"
            "    )\n"
            "\n"
            "meta = json.loads((FEATURE_DIR / \"meta.json\").read_text())\n"
            "print(f\"trace_context        = {meta.get('trace_context')}\")\n"
            "print(f\"require_known_author = {meta.get('require_known_author', False)}\")\n"
            "print(f\"min_human_siblings   = {meta.get('min_human_siblings', 0)}\")\n"
            "print(\"feature cache OK — splits found:\", sorted(p.name for p in FEATURE_DIR.glob(\"*.npz\")))\n"
            "print(\"save dir:\", SAVE_DIR)"
        ),
        _md(
            "## 2. Load features and fit the normalizer\n"
            "\n"
            "Both tracks share one `FeatureNormalizer` fit on the **un-normalized** training split. The normalizer's mean/std are saved into every checkpoint so evaluation later applies the same transform."
        ),
        _code(
            "train_ds = FusionFeatureDataset(FEATURE_DIR / \"train.npz\")\n"
            "val_ds   = FusionFeatureDataset(FEATURE_DIR / \"val.npz\")\n"
            "test_ds_raw = FusionFeatureDataset(FEATURE_DIR / \"test.npz\")  # un-normalized — for evaluation later\n"
            "\n"
            "normalizer = FeatureNormalizer.fit(train_ds.raw_arrays())\n"
            "train_ds.apply_normalizer(normalizer)\n"
            "val_ds.apply_normalizer(normalizer)\n"
            "\n"
            "dims = train_ds.dims\n"
            "print(f\"dims                 = {dims}\")\n"
            "print(f\"train / val / test   = {len(train_ds)} / {len(val_ds)} / {len(test_ds_raw)}\")\n"
            "print(f\"train class counts   = {train_ds.class_counts()}\")\n"
            "print(f\"style coverage       = train {train_ds.style_coverage():.1%}, val {val_ds.style_coverage():.1%}, test {test_ds_raw.style_coverage():.1%}\")"
        ),
        _md(
            "## 3. Train the 4 neural fusion models\n"
            "\n"
            "Each `train_one` call runs up to 40 epochs of `MultiFeatureFusion` with the given strategy, keeps the best-val-F1 checkpoint, and writes `<name>.pt` + `<name>.metrics.json` to `models/ready_models/`."
        ),
        _code(
            "neural_paths = {}\n"
            "for method in FUSION_METHODS:\n"
            "    print(f\"\\n{'=' * 60}\\n   neural fusion: {method}\\n{'=' * 60}\")\n"
            "    config = TrainConfig(fusion_method=method)\n"
            "    out_path = SAVE_DIR / f\"fusion_{method}.pt\"\n"
            "    train_neural_one(config, train_ds, val_ds, normalizer, out_path)\n"
            "    neural_paths[method] = out_path"
        ),
        _md(
            "## 4. Train the 6 classical classifiers\n"
            "\n"
            "These flatten the three feature blocks into one 225-dim vector and let the classifier do its own combination. Tree/linear models also report per-extractor importance, surfacing how much each of NELA / StyleDecipher / TRACE drove the prediction.\n"
            "\n"
            "`xgboost` is skipped automatically if not installed; everything else uses scikit-learn."
        ),
        _code(
            "X_train = flatten_features(train_ds.nela, train_ds.style, train_ds.trace)\n"
            "y_train = train_ds.labels\n"
            "X_val   = flatten_features(val_ds.nela,   val_ds.style,   val_ds.trace)\n"
            "y_val   = val_ds.labels\n"
            "print(f\"flattened feature width: {X_train.shape[1]}  (= {dims['nela']} + {dims['style']} + {dims['trace']})\")\n"
            "\n"
            "available = ClassicalClassifier.available_backends()\n"
            "skipped = [b for b in BACKENDS if b not in available]\n"
            "if skipped:\n"
            "    print(f\"skipping unavailable backends: {skipped}\")\n"
            "\n"
            "classical_paths = {}\n"
            "overrides = {\"n_estimators\": None, \"max_depth\": None, \"learning_rate\": None}\n"
            "for backend in available:\n"
            "    print(f\"\\n{'=' * 60}\\n   classical: {backend}\\n{'=' * 60}\")\n"
            "    out_path = SAVE_DIR / f\"clf_{backend}.joblib\"\n"
            "    train_classical_one(\n"
            "        backend, X_train, y_train, X_val, y_val, dims, normalizer, out_path,\n"
            "        seed=42, class_weighting=True, overrides=overrides,\n"
            "    )\n"
            "    classical_paths[backend] = out_path"
        ),
        _md(
            "## 5. Evaluate all 10 on the held-out test split — default threshold (0.5)\n"
            "\n"
            "Each saved checkpoint carries its own copy of the normalizer, so we reload the **un-normalized** test split per evaluation, apply the checkpoint's normalizer, then predict. Identical logic to [`test/evaluate.py`](../test/evaluate.py)."
        ),
        _code(
            "import torch\n"
            "\n"
            "TEST_NPZ = FEATURE_DIR / \"test.npz\"\n"
            "\n"
            "def predict(model_path):\n"
            "    \"\"\"Return (preds, ai_probs, labels) for either a .pt or .joblib checkpoint.\"\"\"\n"
            "    ds = FusionFeatureDataset(TEST_NPZ)\n"
            "\n"
            "    if model_path.suffix == \".pt\":\n"
            "        model, payload = FusionClassifier.load(model_path, map_location=\"cpu\")\n"
            "        norm = FeatureNormalizer.from_state_dict(payload.get(\"normalizer\"))\n"
            "        if norm is not None:\n"
            "            ds.apply_normalizer(norm)\n"
            "        model.eval()\n"
            "        with torch.no_grad():\n"
            "            logits = model(\n"
            "                torch.from_numpy(ds.nela),\n"
            "                torch.from_numpy(ds.style),\n"
            "                torch.from_numpy(ds.trace),\n"
            "            )\n"
            "            probs = torch.softmax(logits, dim=-1)[:, 1].numpy()\n"
            "            preds = logits.argmax(dim=-1).numpy()\n"
            "    else:\n"
            "        clf, payload = ClassicalClassifier.load(model_path)\n"
            "        norm = FeatureNormalizer.from_state_dict(payload.get(\"normalizer\"))\n"
            "        if norm is not None:\n"
            "            ds.apply_normalizer(norm)\n"
            "        X = flatten_features(ds.nela, ds.style, ds.trace)\n"
            "        probs = clf.predict_proba(X)[:, 1]\n"
            "        preds = clf.predict(X)\n"
            "\n"
            "    return preds.astype(int), probs.astype(float), ds.labels.astype(int)\n"
            "\n"
            "all_models = {f\"neural_{m}\": p for m, p in neural_paths.items()}\n"
            "all_models.update({f\"classical_{b}\": p for b, p in classical_paths.items()})\n"
            "print(\"models to evaluate:\")\n"
            "for k, v in all_models.items():\n"
            "    print(f\"  {k:<32} {v.name}\")"
        ),
        _code(
            "# Run prediction for every model once; reuse probs/preds in subsequent cells.\n"
            "predictions = {}\n"
            "for name, path in all_models.items():\n"
            "    preds, probs, labels = predict(path)\n"
            "    predictions[name] = {\"preds\": preds, \"probs\": probs, \"labels\": labels}\n"
            "    acc = accuracy_score(labels, preds)\n"
            "    mF1 = f1_score(labels, preds, average=\"macro\", zero_division=0)\n"
            "    auc = roc_auc_score(labels, probs)\n"
            "    print(f\"  {name:<32} acc={acc:.4f}  macroF1={mF1:.4f}  ROC-AUC={auc:.4f}\")"
        ),
        _code(
            "# Confusion matrix per model at default threshold (=argmax / 0.5).\n"
            "# Layout: rows = true class, cols = predicted class. Positive class (1) = AI.\n"
            "\n"
            "def fmt_cm(cm, label_names=(\"human\", \"ai\")):\n"
            "    out = [\"            \" + \"\".join(f\"{n:>8}\" for n in label_names)]\n"
            "    for i, n in enumerate(label_names):\n"
            "        out.append(f\"  true {n:<5}\" + \"\".join(f\"{int(v):>8}\" for v in cm[i]))\n"
            "    return \"\\n\".join(out)\n"
            "\n"
            "for name in all_models:\n"
            "    p = predictions[name]\n"
            "    cm = confusion_matrix(p[\"labels\"], p[\"preds\"], labels=[0, 1])\n"
            "    print(f\"\\n=== {name} ===\")\n"
            "    print(fmt_cm(cm))"
        ),
        _md(
            "## 6. Threshold tuning — enforce **FPR ≤ 1 %** (humans falsely flagged as AI)\n"
            "\n"
            "Positive class = AI ⇒ a **false positive is a human text predicted as AI**. The default 0.5 threshold optimises accuracy but admits a relatively high FPR. To deploy the detector for screening (where wrongly accusing humans is much worse than missing an AI), we want **FPR ≤ 1 %** while keeping AI recall (TPR) as high as possible.\n"
            "\n"
            "**Methodology** (avoids test-set leakage):\n"
            "1. For each model, scan thresholds on the **validation** AI-probabilities and pick the *lowest* threshold whose val-FPR ≤ 0.01 (= highest TPR subject to the constraint).\n"
            "2. Apply that threshold to the **test** probabilities and report the actual FPR / TPR / precision / confusion matrix it produces there.\n"
            "\n"
            "If a model's val FPR can't reach 0.01 at any threshold (e.g. it's overconfident on humans), we mark it infeasible.\n"
            "\n"
            "**Note on imbalance.** After the ≥2-sibling filter, the kept set is USE-only and the human:AI ratio is a clean ~1:4.76 in every split. The strict-FPR regime is unaffected — it operates on per-class rates, not counts."
        ),
        _code(
            "# Compute val probs once per model (parallel structure to predict() but for val split).\n"
            "VAL_NPZ = FEATURE_DIR / \"val.npz\"\n"
            "\n"
            "def predict_val(model_path):\n"
            "    ds = FusionFeatureDataset(VAL_NPZ)\n"
            "    if model_path.suffix == \".pt\":\n"
            "        model, payload = FusionClassifier.load(model_path, map_location=\"cpu\")\n"
            "        norm = FeatureNormalizer.from_state_dict(payload.get(\"normalizer\"))\n"
            "        if norm is not None:\n"
            "            ds.apply_normalizer(norm)\n"
            "        model.eval()\n"
            "        with torch.no_grad():\n"
            "            logits = model(\n"
            "                torch.from_numpy(ds.nela),\n"
            "                torch.from_numpy(ds.style),\n"
            "                torch.from_numpy(ds.trace),\n"
            "            )\n"
            "            probs = torch.softmax(logits, dim=-1)[:, 1].numpy()\n"
            "    else:\n"
            "        clf, payload = ClassicalClassifier.load(model_path)\n"
            "        norm = FeatureNormalizer.from_state_dict(payload.get(\"normalizer\"))\n"
            "        if norm is not None:\n"
            "            ds.apply_normalizer(norm)\n"
            "        X = flatten_features(ds.nela, ds.style, ds.trace)\n"
            "        probs = clf.predict_proba(X)[:, 1]\n"
            "    return probs.astype(float), ds.labels.astype(int)\n"
            "\n"
            "\n"
            "def pick_threshold(val_probs, val_labels, max_fpr=0.01):\n"
            "    \"\"\"Highest TPR threshold whose FPR on val is ≤ max_fpr.\"\"\"\n"
            "    fpr_arr, tpr_arr, thr_arr = roc_curve(val_labels, val_probs)\n"
            "    feasible = fpr_arr <= max_fpr\n"
            "    if not feasible.any():\n"
            "        return None, None, None\n"
            "    # roc_curve sorts thresholds descending → fpr/tpr ascending. We want the LAST\n"
            "    # index where fpr ≤ max_fpr (largest tpr that still respects the constraint).\n"
            "    idx = int(np.where(feasible)[0][-1])\n"
            "    return float(thr_arr[idx]), float(fpr_arr[idx]), float(tpr_arr[idx])\n"
            "\n"
            "\n"
            "def metrics_at_threshold(probs, labels, threshold):\n"
            "    preds = (probs >= threshold).astype(int)\n"
            "    cm = confusion_matrix(labels, preds, labels=[0, 1])\n"
            "    tn, fp, fn, tp = cm.ravel()\n"
            "    fpr = fp / (fp + tn) if (fp + tn) else 0.0\n"
            "    tpr = tp / (tp + fn) if (tp + fn) else 0.0\n"
            "    prec = tp / (tp + fp) if (tp + fp) else 0.0\n"
            "    acc = (tp + tn) / cm.sum()\n"
            "    return {\"fpr\": fpr, \"tpr\": tpr, \"precision\": prec, \"accuracy\": acc, \"cm\": cm}"
        ),
        _code(
            "MAX_FPR = 0.01\n"
            "\n"
            "strict_results = {}\n"
            "for name, path in all_models.items():\n"
            "    val_probs, val_labels = predict_val(path)\n"
            "    thr, val_fpr, val_tpr = pick_threshold(val_probs, val_labels, max_fpr=MAX_FPR)\n"
            "\n"
            "    if thr is None:\n"
            "        print(f\"\\n=== {name} ===  INFEASIBLE — no threshold achieves val FPR ≤ {MAX_FPR:.0%}\")\n"
            "        strict_results[name] = None\n"
            "        continue\n"
            "\n"
            "    test_p = predictions[name]\n"
            "    test_metrics = metrics_at_threshold(test_p[\"probs\"], test_p[\"labels\"], thr)\n"
            "    strict_results[name] = {\"threshold\": thr, \"val_fpr\": val_fpr, \"val_tpr\": val_tpr, **test_metrics}\n"
            "\n"
            "    print(f\"\\n=== {name} ===\")\n"
            "    print(f\"  threshold (picked on val)  : {thr:.4f}\")\n"
            "    print(f\"  val   FPR / TPR @ threshold: {val_fpr:.4f} / {val_tpr:.4f}\")\n"
            "    print(f\"  test  FPR / TPR @ threshold: {test_metrics['fpr']:.4f} / {test_metrics['tpr']:.4f}\")\n"
            "    print(f\"  test  precision / accuracy : {test_metrics['precision']:.4f} / {test_metrics['accuracy']:.4f}\")\n"
            "    print(\"  test confusion matrix:\")\n"
            "    print(fmt_cm(test_metrics[\"cm\"]))"
        ),
        _md(
            "## 7. Side-by-side comparison: default 0.5 vs FPR ≤ 1 %\n"
            "\n"
            "The two regimes answer different questions:\n"
            "* **default (argmax)** — what's the best balanced accuracy?\n"
            "* **FPR ≤ 1 %** — if I refuse to wrongly accuse more than 1 % of humans, what fraction of AI text can I still catch?"
        ),
        _code(
            "import pandas as pd\n"
            "\n"
            "rows = []\n"
            "for name in all_models:\n"
            "    p = predictions[name]\n"
            "    cm_def = confusion_matrix(p[\"labels\"], p[\"preds\"], labels=[0, 1])\n"
            "    tn, fp, fn, tp = cm_def.ravel()\n"
            "    fpr_def = fp / (fp + tn) if (fp + tn) else 0.0\n"
            "    tpr_def = tp / (tp + fn) if (tp + fn) else 0.0\n"
            "\n"
            "    sr = strict_results.get(name)\n"
            "    row = {\n"
            "        \"model\":           name,\n"
            "        \"acc@0.5\":         accuracy_score(p[\"labels\"], p[\"preds\"]),\n"
            "        \"macroF1@0.5\":     f1_score(p[\"labels\"], p[\"preds\"], average=\"macro\", zero_division=0),\n"
            "        \"ROC-AUC\":         roc_auc_score(p[\"labels\"], p[\"probs\"]),\n"
            "        \"FPR@0.5\":         fpr_def,\n"
            "        \"TPR@0.5\":         tpr_def,\n"
            "        \"threshold@FPR\\u22641%\": sr[\"threshold\"] if sr else float(\"nan\"),\n"
            "        \"FPR@strict\":      sr[\"fpr\"]       if sr else float(\"nan\"),\n"
            "        \"TPR@strict\":      sr[\"tpr\"]       if sr else float(\"nan\"),\n"
            "        \"precision@strict\":sr[\"precision\"] if sr else float(\"nan\"),\n"
            "    }\n"
            "    rows.append(row)\n"
            "\n"
            "df = pd.DataFrame(rows).sort_values(\"TPR@strict\", ascending=False).reset_index(drop=True)\n"
            "pd.set_option(\"display.float_format\", lambda v: f\"{v:.4f}\")\n"
            "df"
        ),
        _md(
            "## 8. Persist the comparison + verify saved checkpoints\n"
            "\n"
            "Writes `models/ready_models/pipeline_summary.json` next to the checkpoints so the comparison survives the notebook session and can be diffed across re-runs."
        ),
        _code(
            "summary = {\n"
            "    \"max_fpr_constraint\": MAX_FPR,\n"
            "    \"trace_context\": meta.get(\"trace_context\"),\n"
            "    \"require_known_author\": meta.get(\"require_known_author\", False),\n"
            "    \"min_human_siblings\": meta.get(\"min_human_siblings\", 0),\n"
            "    \"models\": [],\n"
            "}\n"
            "for _, r in df.iterrows():\n"
            "    summary[\"models\"].append({k: (None if (isinstance(v, float) and np.isnan(v)) else v) for k, v in r.items()})\n"
            "\n"
            "summary_path = SAVE_DIR / \"pipeline_summary.json\"\n"
            "summary_path.write_text(json.dumps(summary, indent=2))\n"
            "print(f\"wrote {summary_path}\\n\")\n"
            "\n"
            "print(\"saved checkpoints in\", SAVE_DIR)\n"
            "for p in sorted(SAVE_DIR.iterdir()):\n"
            "    if p.suffix in (\".pt\", \".joblib\"):\n"
            "        print(f\"  {p.name:<32} {p.stat().st_size/1024:>10.1f} KB\")\n"
            "    elif p.suffix == \".json\":\n"
            "        print(f\"  {p.name:<32} {p.stat().st_size/1024:>10.1f} KB  (metrics / summary)\")"
        ),
        _md(
            "## 9. Reading the results\n"
            "\n"
            "* **`acc@0.5`, `macroF1@0.5`** — standard headline numbers from `argmax` predictions.\n"
            "* **`ROC-AUC`** — threshold-free ranking quality. A high AUC with a low `TPR@strict` means the model ranks samples correctly but its probabilities aren't sharp enough for a strict cutoff.\n"
            "* **`FPR@strict`** — measured on the test set; should be close to (but may slightly exceed) 0.01 because the threshold was picked on val.\n"
            "* **`TPR@strict`** — the key deployment number: \"if I'm allowed to wrongly accuse ≤ 1 % of humans, what fraction of AI text do I catch?\".\n"
            "* **`precision@strict`** — among everything the model flags as AI under the strict regime, what fraction really is AI.\n"
            "\n"
            "All 10 checkpoints are now in [`../models/ready_models/`](../models/ready_models/) and can be loaded later with:\n"
            "\n"
            "```bash\n"
            "python -m test.evaluate --model models/ready_models/fusion_gating.pt\n"
            "python -m test.evaluate --model models/ready_models/clf_xgboost.joblib\n"
            "```\n"
            "\n"
            "See [`README.md`](README.md) for the training-framework documentation and [`../README.md`](../README.md) for the project overview."
        ),
    ]

    nb = _load(nb_path)
    nb["cells"] = cells
    _save(nb_path, nb)
    print(f"wrote {nb_path}  ({len(cells)} cells)")


# ---------------------------------------------------------------------------
# 3. models/analysis.ipynb
# ---------------------------------------------------------------------------

def rewrite_analysis(nb_path: Path) -> None:
    cells = [
        _md(
            "# Cross-model analysis\n"
            "\n"
            "Post-training analysis of the 11 saved checkpoints in `models/ready_models/`. Answers:\n"
            "\n"
            "1. Which extractor (NELA / StyleDecipher / TRACE) actually drives the predictions?\n"
            "2. Which individual features matter most?\n"
            "3. How do all models compare under default (0.5) and strict (FPR ≤ 1 %) thresholds?\n"
            "4. Where do they agree, and where do they disagree?\n"
            "5. Are there per-source-corpus weaknesses any model has?\n"
            "\n"
            "All evaluation is on the held-out **test** split (829 records — USE-only after the ≥2-sibling filter) using TRACE in `author` mode with same-author HUMAN siblings only."
        ),
        _md("## 1. Setup"),
        _code(
            "import sys, json\n"
            "from pathlib import Path\n"
            "from collections import defaultdict\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import joblib\n"
            "import torch\n"
            "\n"
            "from sklearn.metrics import (\n"
            "    roc_curve, roc_auc_score, accuracy_score, confusion_matrix,\n"
            ")\n"
            "\n"
            "NB_DIR    = Path.cwd()\n"
            "REPO_ROOT = NB_DIR.parent if NB_DIR.name == \"models\" else NB_DIR\n"
            "if str(REPO_ROOT) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO_ROOT))\n"
            "\n"
            "MODELS_DIR  = REPO_ROOT / \"models\" / \"ready_models\"\n"
            "FEATURE_DIR = REPO_ROOT / \"data\"   / \"features\"\n"
            "\n"
            "from training.feature_dataset import FeatureNormalizer, FusionFeatureDataset\n"
            "from training.classical import ClassicalClassifier, flatten_features, block_importances\n"
            "from training.model import FusionClassifier\n"
            "\n"
            "all_paths = sorted(\n"
            "    [p for p in MODELS_DIR.glob(\"fusion_*.pt\")] +\n"
            "    [p for p in MODELS_DIR.glob(\"clf_*.joblib\")]\n"
            ")\n"
            "model_paths = {p.stem: p for p in all_paths}\n"
            "\n"
            "meta = json.loads((FEATURE_DIR / \"meta.json\").read_text())\n"
            "print(f\"cache: trace_context={meta.get('trace_context')!r}  \"\n"
            "      f\"require_known_author={meta.get('require_known_author', False)}  \"\n"
            "      f\"min_human_siblings={meta.get('min_human_siblings', 0)}\")\n"
            "print(f\"found {len(model_paths)} checkpoints:\")\n"
            "for n, p in model_paths.items():\n"
            "    print(f\"  {n:<30} {p.stat().st_size/1024:>10.1f} KB\")"
        ),
        _md(
            "## 2. Performance overview — both regimes\n"
            "\n"
            "Pulled from `pipeline_summary.json` (written by `training/full_pipeline.ipynb`)."
        ),
        _code(
            "summary_path = MODELS_DIR / \"pipeline_summary.json\"\n"
            "summary = json.loads(summary_path.read_text())\n"
            "\n"
            "df = pd.DataFrame(summary[\"models\"]).set_index(\"model\")\n"
            "pd.set_option(\"display.float_format\", lambda v: f\"{v:.4f}\")\n"
            "df.sort_values(\"TPR@strict\", ascending=False)"
        ),
        _code(
            "# Bar chart: macro-F1 at default vs TPR at FPR<=1%\n"
            "ordered = df.sort_values(\"TPR@strict\", ascending=True)\n"
            "\n"
            "fig, axes = plt.subplots(1, 2, figsize=(13, 6), sharey=True)\n"
            "\n"
            "axes[0].barh(ordered.index, ordered[\"macroF1@0.5\"], color=\"#4c78a8\")\n"
            "axes[0].set_xlim(0.85, 1.0)\n"
            "axes[0].set_xlabel(\"macro-F1 @ default (0.5)\")\n"
            "axes[0].set_title(\"Default threshold\")\n"
            "axes[0].grid(axis=\"x\", linestyle=\":\", alpha=0.5)\n"
            "for i, v in enumerate(ordered[\"macroF1@0.5\"]):\n"
            "    axes[0].text(v + 0.002, i, f\"{v:.3f}\", va=\"center\", fontsize=8)\n"
            "\n"
            "axes[1].barh(ordered.index, ordered[\"TPR@strict\"], color=\"#e45756\")\n"
            "axes[1].set_xlim(0.55, 1.0)\n"
            "axes[1].set_xlabel(\"TPR @ FPR\\u22641 % (strict)\")\n"
            "axes[1].set_title(\"Strict regime (max FPR = 1 %)\")\n"
            "axes[1].grid(axis=\"x\", linestyle=\":\", alpha=0.5)\n"
            "for i, v in enumerate(ordered[\"TPR@strict\"]):\n"
            "    axes[1].text(v + 0.005, i, f\"{v:.3f}\", va=\"center\", fontsize=8)\n"
            "\n"
            "plt.suptitle(\"All 11 models — accuracy vs deployment recall\", fontsize=12)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        _md(
            "## 3. Per-extractor importance (NELA vs StyleDecipher vs TRACE)\n"
            "\n"
            "Each classical model's importance vector is split into the three feature blocks and summed. This answers the central question of this repo: *how much does each extractor contribute?* TRACE importance here reflects the **author-mode** embedding (same-author HUMAN siblings, no source-text leakage) — typically a different signal than the single-text embedding used before the 2026-05-26 rebuild.\n"
            "\n"
            "(Neural fusion models don't expose interpretable per-feature weights, and SVM/MLP/hist_gbm classical backends don't expose `feature_importances_` either — they're absent here.)"
        ),
        _code(
            "DIMS = {\"nela\": 87, \"style\": 10, \"trace\": 128}\n"
            "\n"
            "ei_rows = []\n"
            "for name, p in model_paths.items():\n"
            "    if p.suffix != \".joblib\":\n"
            "        continue\n"
            "    payload = joblib.load(p)\n"
            "    est = payload[\"estimator\"]\n"
            "    if hasattr(est, \"feature_importances_\"):\n"
            "        imp = np.asarray(est.feature_importances_, dtype=float)\n"
            "    elif hasattr(est, \"coef_\"):\n"
            "        imp = np.abs(np.asarray(est.coef_, dtype=float)).flatten()\n"
            "    else:\n"
            "        continue\n"
            "    blocks = block_importances(imp, DIMS)\n"
            "    ei_rows.append({\"model\": name, **blocks})\n"
            "\n"
            "ei_df = pd.DataFrame(ei_rows).set_index(\"model\").sort_values(\"nela\", ascending=True)\n"
            "ei_df"
        ),
        _code(
            "# Stacked horizontal bar: per-extractor share of each model's decision\n"
            "fig, ax = plt.subplots(figsize=(11, max(3, len(ei_df) * 0.6)))\n"
            "left = np.zeros(len(ei_df))\n"
            "for block, colour in zip([\"nela\", \"style\", \"trace\"], [\"#4c78a8\", \"#f58518\", \"#54a24b\"]):\n"
            "    vals = ei_df[block].values\n"
            "    ax.barh(ei_df.index, vals, left=left, color=colour, label=block.upper())\n"
            "    for i, (l, v) in enumerate(zip(left, vals)):\n"
            "        if v > 0.04:\n"
            "            ax.text(l + v/2, i, f\"{v:.0%}\", va=\"center\", ha=\"center\", color=\"white\", fontsize=9, fontweight=\"bold\")\n"
            "    left += vals\n"
            "ax.set_xlim(0, 1.0)\n"
            "ax.set_xlabel(\"share of total feature importance\")\n"
            "ax.set_title(\"Per-extractor importance per classical model\")\n"
            "ax.legend(loc=\"lower right\")\n"
            "ax.grid(axis=\"x\", linestyle=\":\", alpha=0.4)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        _md(
            "**Reading:** NELA typically carries the bulk of every model's decision (it has 87 of the 225 dims and most of them are individually discriminative). TRACE is the second contributor — *more so under author mode*, because the embedding now reflects same-author writing-style context rather than just the single text. StyleDecipher contributes least everywhere, but with 100 % coverage it still adds real signal, especially through `style_mean_cos` and `style_mean_2g`."
        ),
        _md(
            "## 4. Top individual features — which named features matter most?\n"
            "\n"
            "For each classical model with interpretable weights, we map the 225 features back to their names:\n"
            "* dims 0–86  → NELA (POS counts, readability, sentiment, moral foundations …)\n"
            "* dims 87–96 → StyleDecipher (mean/std of n-gram overlap, edit similarity, cosine similarity vs rewrites)\n"
            "* dims 97–224 → TRACE latent embedding (uninterpretable individually)"
        ),
        _code(
            "# Hard-coded feature names so this notebook runs without re-loading NELA / NLTK.\n"
            "NELA_NAMES = [\n"
            "    \"quotes\",\"exclaim\",\"allpunc\",\"allcaps\",\"stops\",\n"
            "    \"CC\",\"CD\",\"DT\",\"EX\",\"FW\",\"IN\",\"JJ\",\"JJR\",\"JJS\",\"LS\",\"MD\",\n"
            "    \"NN\",\"NNS\",\"NNP\",\"NNPS\",\"PDT\",\"POS\",\"PRP\",\"PRP$\",\n"
            "    \"RB\",\"RBR\",\"RBS\",\"RP\",\"SYM\",\"TO\",\"UH\",\"WP$\",\"WRB\",\n"
            "    \"VB\",\"VBD\",\"VBG\",\"VBN\",\"VBP\",\"VBZ\",\"WDT\",\"WP\",\n"
            "    \"$\",\"''\",\"(\",\")\",\",\",\"--\",\".\",\":\",\"``\",\n"
            "    \"ttr\",\"avg_wordlen\",\"word_count\",\n"
            "    \"flesch_kincaid_grade_level\",\"smog_index\",\"coleman_liau_index\",\"lix\",\n"
            "    \"bias_words\",\"assertatives\",\"factives\",\"hedges\",\"implicatives\",\"report_verbs\",\n"
            "    \"positive_opinion_words\",\"negative_opinion_words\",\n"
            "    \"vadneg\",\"vadneu\",\"vadpos\",\"wneg\",\"wpos\",\"wneu\",\"sneg\",\"spos\",\"sneu\",\n"
            "    \"HarmVirtue\",\"HarmVice\",\"FairnessVirtue\",\"FairnessVice\",\n"
            "    \"IngroupVirtue\",\"IngroupVice\",\"AuthorityVirtue\",\"AuthorityVice\",\n"
            "    \"PurityVirtue\",\"PurityVice\",\"MoralityGeneral\",\n"
            "    \"num_locations\",\"num_dates\",\n"
            "]\n"
            "STYLE_NAMES = [\n"
            "    \"style_mean_1g\",\"style_mean_2g\",\"style_mean_3g\",\"style_mean_edit\",\"style_mean_cos\",\n"
            "    \"style_std_1g\", \"style_std_2g\", \"style_std_3g\", \"style_std_edit\", \"style_std_cos\",\n"
            "]\n"
            "TRACE_NAMES = [f\"trace_{i:03d}\" for i in range(128)]\n"
            "ALL_NAMES = NELA_NAMES + STYLE_NAMES + TRACE_NAMES\n"
            "assert len(ALL_NAMES) == 225, f\"feature-name list mismatch: {len(ALL_NAMES)}\"\n"
            "\n"
            "BLOCK_OF = {i: \"nela\" for i in range(87)}\n"
            "BLOCK_OF.update({i: \"style\" for i in range(87, 97)})\n"
            "BLOCK_OF.update({i: \"trace\" for i in range(97, 225)})"
        ),
        _code(
            "TOP_K = 10\n"
            "\n"
            "for name, p in model_paths.items():\n"
            "    if p.suffix != \".joblib\":\n"
            "        continue\n"
            "    payload = joblib.load(p)\n"
            "    est = payload[\"estimator\"]\n"
            "    if hasattr(est, \"feature_importances_\"):\n"
            "        imp = np.asarray(est.feature_importances_, dtype=float)\n"
            "        kind = \"tree importance\"\n"
            "    elif hasattr(est, \"coef_\"):\n"
            "        imp = np.abs(np.asarray(est.coef_, dtype=float)).flatten()\n"
            "        kind = \"|coef|\"\n"
            "    else:\n"
            "        continue\n"
            "    order = imp.argsort()[::-1]\n"
            "\n"
            "    print(f\"\\n=== {name}  ({kind}) ===\")\n"
            "    print(f\"  top {TOP_K} features overall:\")\n"
            "    for r, idx in enumerate(order[:TOP_K], 1):\n"
            "        block = BLOCK_OF[idx]\n"
            "        print(f\"    {r:>2}. [{block:<5}] {ALL_NAMES[idx]:<35} {imp[idx]:.4f}\")"
        ),
        _code(
            "# Aggregate across all classical models: which features show up in the top-K most often?\n"
            "appearances = defaultdict(int)\n"
            "weight_sum  = defaultdict(float)\n"
            "n_models    = 0\n"
            "\n"
            "for name, p in model_paths.items():\n"
            "    if p.suffix != \".joblib\":\n"
            "        continue\n"
            "    payload = joblib.load(p)\n"
            "    est = payload[\"estimator\"]\n"
            "    if hasattr(est, \"feature_importances_\"):\n"
            "        imp = np.asarray(est.feature_importances_, dtype=float)\n"
            "    elif hasattr(est, \"coef_\"):\n"
            "        imp = np.abs(np.asarray(est.coef_, dtype=float)).flatten()\n"
            "    else:\n"
            "        continue\n"
            "    n_models += 1\n"
            "    norm = imp / (imp.sum() or 1.0)\n"
            "    for idx in norm.argsort()[::-1][:TOP_K]:\n"
            "        appearances[idx] += 1\n"
            "        weight_sum[idx]  += float(norm[idx])\n"
            "\n"
            "agg = pd.DataFrame([\n"
            "    {\n"
            "        \"feature\":  ALL_NAMES[idx],\n"
            "        \"block\":    BLOCK_OF[idx],\n"
            "        \"in_top_K\": appearances[idx],\n"
            "        \"mean_importance\": weight_sum[idx] / appearances[idx],\n"
            "    }\n"
            "    for idx in appearances\n"
            "])\n"
            "agg = agg.sort_values([\"in_top_K\", \"mean_importance\"], ascending=False).reset_index(drop=True)\n"
            "print(f\"features appearing in the top-{TOP_K} of >=1 of {n_models} interpretable classical models:\")\n"
            "agg"
        ),
        _md(
            "**Reading:** Features at the top of this aggregate are the ones repeatedly chosen by multiple independent classifiers as discriminative for human-vs-AI. POS-tag rates, readability indices, and lexical-diversity measures from NELA tend to dominate. Now that TRACE is author-aware, watch whether the top TRACE dims (`trace_NNN`) start showing up more often than they did under single-text mode — that's the direct signal that author context is adding value beyond raw stylistic surface features."
        ),
        _md("## 5. ROC curves — overlaid for every model"),
        _code(
            "TEST_NPZ = FEATURE_DIR / \"test.npz\"\n"
            "\n"
            "def predict(model_path):\n"
            "    \"\"\"Return (preds, ai_probs, labels, sources) for either a .pt or .joblib checkpoint.\"\"\"\n"
            "    ds = FusionFeatureDataset(TEST_NPZ)\n"
            "    if model_path.suffix == \".pt\":\n"
            "        model, payload = FusionClassifier.load(model_path, map_location=\"cpu\")\n"
            "        norm = FeatureNormalizer.from_state_dict(payload.get(\"normalizer\"))\n"
            "        if norm is not None:\n"
            "            ds.apply_normalizer(norm)\n"
            "        model.eval()\n"
            "        with torch.no_grad():\n"
            "            logits = model(\n"
            "                torch.from_numpy(ds.nela),\n"
            "                torch.from_numpy(ds.style),\n"
            "                torch.from_numpy(ds.trace),\n"
            "            )\n"
            "            probs = torch.softmax(logits, dim=-1)[:, 1].numpy()\n"
            "            preds = logits.argmax(dim=-1).numpy()\n"
            "    else:\n"
            "        clf, payload = ClassicalClassifier.load(model_path)\n"
            "        norm = FeatureNormalizer.from_state_dict(payload.get(\"normalizer\"))\n"
            "        if norm is not None:\n"
            "            ds.apply_normalizer(norm)\n"
            "        X = flatten_features(ds.nela, ds.style, ds.trace)\n"
            "        probs = clf.predict_proba(X)[:, 1]\n"
            "        preds = clf.predict(X)\n"
            "    return preds.astype(int), probs.astype(float), ds.labels.astype(int), ds.sources\n"
            "\n"
            "preds_cache = {}\n"
            "for name, p in model_paths.items():\n"
            "    preds_cache[name] = predict(p)\n"
            "    yp, yprob, y, _ = preds_cache[name]\n"
            "    print(f\"  {name:<30} acc={accuracy_score(y, yp):.4f}  AUC={roc_auc_score(y, yprob):.4f}\")"
        ),
        _code(
            "fig, ax = plt.subplots(figsize=(8, 8))\n"
            "for name, (_, probs, labels, _) in preds_cache.items():\n"
            "    fpr, tpr, _ = roc_curve(labels, probs)\n"
            "    auc = roc_auc_score(labels, probs)\n"
            "    ax.plot(fpr, tpr, label=f\"{name}  (AUC={auc:.4f})\", lw=1.5, alpha=0.85)\n"
            "\n"
            "ax.plot([0, 1], [0, 1], color=\"grey\", lw=0.8, linestyle=\"--\", label=\"chance\")\n"
            "ax.axvline(0.01, color=\"red\", lw=0.8, linestyle=\":\", alpha=0.7)\n"
            "ax.text(0.012, 0.05, \"FPR = 1 %\", color=\"red\", fontsize=8)\n"
            "ax.set_xlim(0, 0.2)\n"
            "ax.set_ylim(0.7, 1.001)\n"
            "ax.set_xlabel(\"False Positive Rate (humans flagged as AI)\")\n"
            "ax.set_ylabel(\"True Positive Rate (AI caught)\")\n"
            "ax.set_title(\"ROC curves on the test split (zoomed to low FPR)\")\n"
            "ax.grid(linestyle=\":\", alpha=0.5)\n"
            "ax.legend(loc=\"lower right\", fontsize=7)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        _md(
            "**Reading:** zoomed to the deployment-relevant low-FPR region. The model that's furthest *up* at the red FPR=1 % line wins under the strict constraint. Crowded at the top-left = excellent ranking quality across the board (most AUCs > 0.99)."
        ),
        _md(
            "## 6. Per-source accuracy — where does each model struggle?\n"
            "\n"
            "After `min_human_siblings=2`, the test split has only **2 source corpora**:\n"
            "* `use` (144) — original human essays from USE authors with ≥3 essays\n"
            "* `use_rewrite` (685) — 5 LLM paraphrases of each of those essays\n"
            "\n"
            "All non-USE sources (HC3-AI, ArguGPT, RAID) are dropped because their generator-as-author has no human siblings. The per-source view is therefore a two-column comparison: how well does each model spot human originals vs LLM rewrites? This is the *style-shift* test the dataset was designed for."
        ),
        _code(
            "rows = []\n"
            "for name, (preds, _, labels, sources) in preds_cache.items():\n"
            "    row = {\"model\": name}\n"
            "    for src in sorted(set(str(s) for s in sources)):\n"
            "        mask = np.array([str(s) == src for s in sources])\n"
            "        if mask.any():\n"
            "            row[src] = accuracy_score(labels[mask], preds[mask])\n"
            "    rows.append(row)\n"
            "\n"
            "per_src = pd.DataFrame(rows).set_index(\"model\").sort_index()\n"
            "per_src"
        ),
        _code(
            "# Heatmap: model x source corpus, cell = accuracy\n"
            "fig, ax = plt.subplots(figsize=(8, max(4, len(per_src) * 0.45)))\n"
            "data = per_src.values\n"
            "im = ax.imshow(data, cmap=\"RdYlGn\", vmin=0.6, vmax=1.0, aspect=\"auto\")\n"
            "ax.set_xticks(range(len(per_src.columns)))\n"
            "ax.set_xticklabels(per_src.columns, rotation=30, ha=\"right\")\n"
            "ax.set_yticks(range(len(per_src.index)))\n"
            "ax.set_yticklabels(per_src.index)\n"
            "for i in range(data.shape[0]):\n"
            "    for j in range(data.shape[1]):\n"
            "        ax.text(j, i, f\"{data[i,j]:.3f}\", ha=\"center\", va=\"center\", color=\"black\", fontsize=8)\n"
            "plt.colorbar(im, ax=ax, label=\"accuracy\")\n"
            "ax.set_title(\"Per-source-corpus accuracy on test (default 0.5 threshold)\")\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        _md(
            "**Reading:** with only `use` and `use_rewrite` left, the heat-map answers one question: does the model treat *the same author's* humans and LLM rewrites differently? A green `use` column = good at recognising the real essay; a green `use_rewrite` column = the model isn't fooled by the paraphrase. Anywhere both columns are green simultaneously is the win condition."
        ),
        _md(
            "## 7. Model agreement — do they ever disagree?\n"
            "\n"
            "For every pair of models, fraction of test records where their hard predictions match."
        ),
        _code(
            "names = list(preds_cache.keys())\n"
            "n = len(names)\n"
            "agree = np.zeros((n, n))\n"
            "for i, a in enumerate(names):\n"
            "    pa = preds_cache[a][0]\n"
            "    for j, b in enumerate(names):\n"
            "        pb = preds_cache[b][0]\n"
            "        agree[i, j] = (pa == pb).mean()\n"
            "\n"
            "fig, ax = plt.subplots(figsize=(9, 8))\n"
            "im = ax.imshow(agree, cmap=\"Blues\", vmin=0.85, vmax=1.0)\n"
            "ax.set_xticks(range(n)); ax.set_xticklabels(names, rotation=45, ha=\"right\")\n"
            "ax.set_yticks(range(n)); ax.set_yticklabels(names)\n"
            "for i in range(n):\n"
            "    for j in range(n):\n"
            "        ax.text(j, i, f\"{agree[i,j]:.3f}\", ha=\"center\", va=\"center\", color=\"black\" if agree[i,j] < 0.97 else \"white\", fontsize=7)\n"
            "plt.colorbar(im, ax=ax, label=\"fraction of records both predict the same class\")\n"
            "ax.set_title(\"Pairwise prediction agreement on test\")\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        _code(
            "# Which records do most models disagree on? (potential 'hard' samples)\n"
            "all_preds = np.stack([preds_cache[n][0] for n in names])  # (n_models, n_records)\n"
            "vote_ai = all_preds.sum(axis=0)                            # how many models said 'ai' per record\n"
            "labels = preds_cache[names[0]][2]\n"
            "sources = preds_cache[names[0]][3]\n"
            "\n"
            "# Records where models are roughly split (between ~25 % and ~75 % vote ai)\n"
            "lo, hi = int(0.3 * n), int(0.7 * n)\n"
            "split_mask = (vote_ai >= lo) & (vote_ai <= hi)\n"
            "print(f\"records where models are split (between {lo} and {hi} of {n} voting AI): {int(split_mask.sum())}\")\n"
            "if split_mask.any():\n"
            "    ai_when_split    = (labels[split_mask] == 1).sum()\n"
            "    human_when_split = (labels[split_mask] == 0).sum()\n"
            "    print(f\"  of those, true label = ai: {ai_when_split}, human: {human_when_split}\")\n"
            "    print(\"  source mix of the contested records:\")\n"
            "    from collections import Counter\n"
            "    for src, c in Counter(str(s) for s in sources[split_mask]).most_common():\n"
            "        print(f\"    {src:<14} {c}\")"
        ),
        _md(
            "**Reading:** with the test split restricted to USE essays and their rewrites, every contested record is by definition a paraphrase pair the models can't agree on. These are the genuine boundary cases for the style-shift task and worth inspecting by hand to understand each model's failure modes."
        ),
        _md(
            "## 8. The `neural_concat` ≡ `neural_mlp` anomaly\n"
            "\n"
            "Previous runs occasionally produced bit-for-bit identical predictions for these two models — either a save-time collision or genuine optimisation convergence. Quick check after the new training run:"
        ),
        _code(
            "concat_path = MODELS_DIR / \"fusion_concat.pt\"\n"
            "mlp_path    = MODELS_DIR / \"fusion_mlp.pt\"\n"
            "\n"
            "if concat_path.exists() and mlp_path.exists():\n"
            "    m1, p1 = FusionClassifier.load(concat_path, map_location=\"cpu\")\n"
            "    m2, p2 = FusionClassifier.load(mlp_path,    map_location=\"cpu\")\n"
            "    print(f\"  concat hparams: {p1['hparams']}\")\n"
            "    print(f\"  mlp    hparams: {p2['hparams']}\")\n"
            "\n"
            "    sd1 = p1[\"state_dict\"]\n"
            "    sd2 = p2[\"state_dict\"]\n"
            "    keys1, keys2 = set(sd1.keys()), set(sd2.keys())\n"
            "    print(f\"\\n  state_dict keys identical: {keys1 == keys2}\")\n"
            "    if keys1 == keys2:\n"
            "        all_same = all(torch.equal(sd1[k], sd2[k]) for k in sd1)\n"
            "        print(f\"  every tensor identical:   {all_same}\")\n"
            "\n"
            "    p1_preds, p1_probs, _, _ = preds_cache[\"fusion_concat\"]\n"
            "    p2_preds, p2_probs, _, _ = preds_cache[\"fusion_mlp\"]\n"
            "    print(f\"\\n  predictions identical: {bool((p1_preds == p2_preds).all())}\")\n"
            "    print(f\"  max |prob_concat - prob_mlp| = {float(np.abs(p1_probs - p2_probs).max()):.2e}\")\n"
            "else:\n"
            "    print(\"one of the checkpoints is missing\")"
        ),
        _md(
            "**Reading:** if `every tensor identical: True` *and* `predictions identical: True`, the two `.pt` files are literally the same model (a training-time or save-time collision). Re-run the neural-training cell in `training/full_pipeline.ipynb` to get a real `fusion_mlp` checkpoint.\n"
            "\n"
            "If hparams differ but every parameter tensor still matches → very unlikely, but it would mean the architectures collapsed onto the same optimum."
        ),
        _md(
            "## 9. Conclusions\n"
            "\n"
            "Re-run the cells above against the fresh 2026-05-26 cache to populate these numbers. The structural conclusions to look for under the new USE-only / author-aware setup:\n"
            "\n"
            "1. **For deployment under FPR ≤ 1 %** — usually a tree ensemble (`hist_gbm` / `xgboost`) wins. Watch whether author-mode TRACE narrows the gap between neural and classical models.\n"
            "2. **For raw accuracy** at the default threshold — neural fusion models tend to lead by ~0.5 % macro-F1 but give up more recall under strict FPR.\n"
            "3. **Per-extractor importance** — NELA usually dominates. Author-mode TRACE *should* show a measurably larger share than the previous single-text TRACE; if it doesn't, the human-only sibling rule isn't adding enough signal beyond NELA's surface features.\n"
            "4. **Per-source accuracy** — only `use` (humans) and `use_rewrite` (LLM paraphrases) remain. A model that nails both columns is genuinely solving the style-shift task; one that only nails `use_rewrite` is exploiting paraphrase artefacts.\n"
            "5. **Where the models disagree** — every contested record is a paraphrase pair from a real USE author. These are the cleanest hard cases to triage."
        ),
    ]

    nb = _load(nb_path)
    nb["cells"] = cells
    _save(nb_path, nb)
    print(f"wrote {nb_path}  ({len(cells)} cells)")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    rewrite_dataset_overview(REPO_ROOT / "data" / "dataset_overview.ipynb")
    rewrite_full_pipeline(REPO_ROOT / "training" / "full_pipeline.ipynb")
    rewrite_analysis(REPO_ROOT / "models" / "analysis.ipynb")


if __name__ == "__main__":
    main()
